POST requests on new threads with bounded queue
resurfaceio/logger-python pull request #32
Opened 2021-02-25 14:34 UTC by monrax

Moved the `try-except` block from `submit` to a new `post_request` function nested inside `submit`, so that it works as a target when creating a new `Thread`. This thread doesn't block the calling thread (so that new submission can be made from the main thread), instead a `max_queue_depth` attribute that defaults to 128 sets the upperbound limit of a `Queue` object, which can block if necessary until a free slot is available. When `submit` is called, given that the logger's `queue` attribute is not `None`, the corresponding `msg` is put in the queue and a new `post_request` thread is started. After each response, the first item in the queue is removed (NOTE: the first thread to have a response will perform the next dequeue operation, thus the item returned from the queue might not necessarily match the `msg` passed to that particular thread)

2021-02-25 14:40 UTC, monrax commented
I assumed that the `queue` attribute of the `BaseLogger` object was intended for this purpose, but I'm not sure that this is the case. Please, let me know if something like this is what you had in mind @RobDickinson

2021-05-07 03:29 UTC, Anyesh commented on tests/test_concurrent_submissions.py
> +    logger = BaseLogger(MOCK_AGENT, url=DEMO_URL)
We removed the demo URL so maybe we should find another way to test

2021-05-07 03:31 UTC, Anyesh requested changes

2021-05-07 03:31 UTC, Anyesh commented on tests/test_concurrent_submissions.py
> +def test_multiple_loggers() -> None:
Since we are checking multiple threads maybe we can assert the activate threads to make sure that multi-thread is running.

2021-05-07 03:34 UTC, Anyesh requested changes

2021-05-07 03:34 UTC, Anyesh commented on tests/test_concurrent_submissions.py
> +from tests.test_helper import *
Also, try not to use wildcard import! I have faded that on my PR #51 merge TBD.

2022-02-14 04:39 UTC, closed without merging